site_name: Epsilon
nav:
  - Home: index.md
  - Download : 'download/index.md'
  - Documentation:
    - Overview: 'doc/index.md'
    - Model connectivity: 'doc/emc.md'    
    - Languages:
        - Object language (EOL): 'doc/eol.md'
        - Code generation (EGL): 'doc/egl.md'
        - Model validation (EVL): 'doc/evl.md'
        - Model transformation (ETL): 'doc/etl.md'
        - Model comparison (ECL): 'doc/ecl.md'
        - Model merging (EML): 'doc/eml.md'
        - Pattern matching (EPL): 'doc/epl.md'
        - Model Migration (Flock): 'doc/flock.md'
        - Model generation (EMG): 'doc/emg.md'
        - Unit testing (EUnit): 'doc/eunit.md'
    - Tools:
        - Picto: 'doc/picto/index.md'
        - Flexmi: 'doc/flexmi/index.md'
        - Eugenia: 'doc/eugenia/index.md'
        - Exeed: 'doc/exeed/index.md'
        - Modelink: 'doc/modelink/index.md'
        - HUTN: 'doc/hutn.md'
        - Workflow (Ant tasks): 'doc/workflow.md'
    - Articles: 'doc/articles/index.md'
    - Screencasts: 'https://www.youtube.com/epsilondevs'
    - Lectures: 'https://www.youtube.com/playlist?list=PLRwHao6Ue0YUecg7vEUQTrtySIWwrd_mI'
    - Javadoc:
      - Stable: 'https://download.eclipse.org/epsilon/2.0/javadoc/'
      - Interim: 'https://download.eclipse.org/epsilon/interim/javadoc/'
  - Community:
      - Who is using Epsilon?:
        - Industry: 'users/index.md'
        - Education: 'users/education.md'
        - Open-source projects: 'users/open-source.md'
      - Who is developing Epsilon?: 'https://projects.eclipse.org/projects/modeling.epsilon/who'
      - Bugzilla:
        - Report a new issue: 'https://bugs.eclipse.org/bugs/enter_bug.cgi?product=epsilon'
        - View open bugs: 'https://bugs.eclipse.org/bugs/buglist.cgi?product=epsilon&cmdtype=doit&order=Reuse+same+sort+as+last+time&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_severity=blocker&bug_severity=critical&bug_severity=major&bug_severity=normal&bug_severity=minor&bug_severity=trivial'
        - View enhancement requests: 'https://bugs.eclipse.org/bugs/buglist.cgi?product=epsilon&cmdtype=doit&order=Reuse+same+sort+as+last+time&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_severity=enhancement'
        - View all issues: 'https://bugs.eclipse.org/bugs/buglist.cgi?product=epsilon&cmdtype=doit&order=Reuse+same+sort+as+last+time'
      - Forum: 'https://www.eclipse.org/forums/index.php/f/22/'
      - Epsilon Labs: 'labs.md'
      - Frequently asked questions: 'faq.md'   
theme: 
  name: material
  custom_dir: custom_theme
  logo: 'assets/images/epsilon-white-background.png'
  palette:
    primary: 'black'
    accent: 'orange'
repo_name: 'Git repository @ Eclipse'
repo_url: 'https://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git/'
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid mermaid-100
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-90
          class: mermaid mermaid-90
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-80
          class: mermaid mermaid-80
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-70
          class: mermaid mermaid-70
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-60
          class: mermaid mermaid-60
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-50
          class: mermaid mermaid-50
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-40
          class: mermaid mermaid-40
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid-30
          class: mermaid mermaid-30
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: eol
          class: prettyprint lang-eol
          format: !!python/name:pymdownx.superfences.fence_code_format  
        - name: etl
          class: prettyprint lang-etl
          format: !!python/name:pymdownx.superfences.fence_code_format  
        - name: ecl
          class: prettyprint lang-ecl
          format: !!python/name:pymdownx.superfences.fence_code_format  
        - name: eml
          class: prettyprint lang-eml
          format: !!python/name:pymdownx.superfences.fence_code_format  
        - name: epl
          class: prettyprint lang-epl
          format: !!python/name:pymdownx.superfences.fence_code_format  
        - name: evl
          class: prettyprint lang-evl
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mig
          class: prettyprint lang-mig
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: eunit
          class: prettyprint lang-eol
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: egx
          class: prettyprint lang-egx
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: egl
          class: prettyprint lang-egl
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: emf
          class: prettyprint lang-emf
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - meta
  - footnotes
  # - pymdownx.tabbed
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
plugins:
    - search
    - redirects:
        redirect_maps:
            'forum': 'https://www.eclipse.org/forums/index.php/f/22/'
            'doc/screencasts' : 'https://www.youtube.com/epsilondevs'
            'doc/lectures' : 'https://www.youtube.com/playlist?list=PLRwHao6Ue0YUecg7vEUQTrtySIWwrd_mI'
            'doc/examples' : 'https://git.eclipse.org/c/epsilon/org.eclipse.epsilon.git/tree/examples'
            'doc/articles/emfatic.md': 'https://www.eclipse.org/emfatic'
            'doc/articles/eugenia-gmf-tutorial/index.md': 'doc/eugenia/index.md'
            'doc/articles/flexmi/index.md': 'doc/flexmi/index.md'
            'doc/articles/picto/index.md': 'doc/picto/index.md'
            'doc/articles/exeed-reference/index.md': 'doc/exeed/index.md'


copyright: 'Copyright © Eclipse Foundation, Inc. All Rights Reserved.'
extra_css:
  - 'assets/stylesheets/extra.css'
  - 'assets/stylesheets/mermaid.css'
  - 'assets/javascript/google-code-prettify/prettify.css'
  #- 'assets/stylesheets/tabbed.css'
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
  - 'assets/javascript/mermaid.js'
  - 'assets/javascript/jquery.js'
  - 'assets/javascript/google-code-prettify/prettify.js'
  - 'assets/javascript/google-code-prettify/lang-emfatic.js'    
  - 'assets/javascript/google-code-prettify/lang-epsilon.js'    
  - 'assets/javascript/google-code-prettify/prettyprint.js'